apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth

resources:
- github.com/kubeflow/manifests/common/dex/overlays/istio

patchesStrategicMerge:
- configmap-patch.yaml

images:
- name: ezee/dex
  newName: ezee/dex
  newTag: v2.28.1
  # digest: sha256:2e114c22c1d96f614c11362c44da1033b92469c8b2d9b3d687d8cd02a9c937ee
