apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "5HIXgddAQlGkWwbBsBab/rwDMi1WERlwlbG8NlBHxUZ7PnuGfEN1se8Ga/2S1lpV\nu0jT7jaA284sAx6tk4CaCmQ7sew5g37l0AjfGDE9+rvoMQUAwLLGPv6BSscPFYyW\nMY8of1oL2VrW+qXfjA1P8aJUpze1n5UV3OuyHKUEnwc="
